name: 'custom_postgres'
version: '1.0.0'
config-version: 2

profile: 'custom_postgres'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']
target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  custom_postgres:
    +materialized: 'table'