version: 2

models:
  - name: films
    description: "Films table"
    columns:
      - name: id
        description: "Unique identifier for each film"
        data_type: integer
        primary_key: true
      - name: title
        description: "Title of the film"
        data_type: varchar(255)
      - name: release_date
        description: "Year the film was released"
        data_type: integer
      - name: price
        type: decimal(5, 2)
        description: "Price of the film"
      - name: rating
        type: varchar(10)
        description: "Film rating (e.g., PG-13, R)"
      - name: user_rating
        type: decimal(2, 1)
        description: "Average user rating for the film"

  - name: actors
    description: "Actors table"
    columns:
      - name: actor_id
        description: "Unique identifier for each actor"
        data_type: integer
        primary_key: true
      - name: actor_name
        description: "Name of the actor"
        data_type: varchar(255)

  - name: film_actors
    description: "Film-Actor relationship table"
    columns:
      - name: film_id
        description: "Unique identifier for each film"
        data_type: integer
        primary_key: true
      - name: actor_id
        description: "ID of the actor"
        data_type: integer